version: "3.7"
services:
  #php with all project needed extensios
  php:
    build:
      context: ./docker
    image: phpdocker
    container_name: fraud-api
    volumes:
      - ".:/var/www/html/"
    depends_on:
      - mongo
      - composerinstall
    networks:
      - fraud_network

  #nginx to hold all nginx server configs
  nginx:
    container_name: fraud-nginx
    build:
      context: ./docker/nginx # The path of the Dockerfile
    volumes:
    - "./public:/var/www/html/public"
    environment:
      NGINX_FPM_HOST: php
      NGINX_ROOT: /var/www/html/public
    ports:
      - "8000:80"
    depends_on:
      - php
    networks:
      - fraud_network

  #mongodb container
  mongo:
    image: mongo:4.4.2-bionic
    container_name: fraud-database
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - "./storage/db-data:/data/db"
    networks:
      - fraud_network

  composerinstall:
    container_name: fraud-composer-install
    build:
        context: ./docker
    volumes:
      - ".:/var/www/html/"
    command: composer install

#network to hold api/nginx/mongo
networks:
  fraud_network:
    driver: bridge
